### ISSUE TITLE
Add spacing between blocks in sidebar

### ISSUE THREAD

**Issue by zipymonkey** [psu-libraries/psulib_base#186]
Currently there is no default spacing between blocks in the sidebar regions.  There should be at least 1rem ($spacer) margin between each.   This could be something like

```css
.region-sidebar-first > div:not(:last-child) {
  margin-bottom: 1rem;
}
```

Example

<img width="455" alt="Screenshot 2024-10-03 at 8 04 23 AM" src="https://github.com/user-attachments/assets/0e0b1f07-db26-4687-a3c1-8663ae98e72a">
