### ISSUE TITLE
Icon paths are incorrect for some file types

### ISSUE THREAD

**Issue by zipymonkey** [psu-libraries/psulib_base#191]
See https://github.com/psu-libraries/intranet/issues/100

There is a bug in the base theme library. The icon paths to several file types is incorrect. Icons starting with ../../images are incorrect.

```css
.file--application-pdf {
    background-image: url(../../images/icons/file-pdf-fill.svg);
}

.file--application-x-executable {
    background-image: url(../../images/icons/filetype-exe.svg);
}

.file--audio {
    background-image: url(../../images/icons/filetype-mp3.svg);
}

.file--video {
    background-image: url(../../images/icons/camera-video-fill.svg);
}
```
