### ISSUE TITLE
Add styles to bootstrap tables that overflow to indicate more content

### ISSUE THREAD

**Issue by zipymonkey** [psu-libraries/psulib_base#196]
When a bootstrap table overflows the overflowing content is hidden but the user can scroll horizontally to see additional content.  This is not clear to the user that there is more content.  Maybe we can add a inset shadow?  Not sure if something like this is possible.

**Comment by zipymonkey** [comment]
Potential solution: https://daverupert.com/2023/08/animation-timeline-scroll-shadows/. This sort of works but the issue is the overlay height being larger than the .table-responsive element.

```scss
.table-responsive {
  animation: scroll-shadow-inset linear;
  animation-timeline: scroll( self inline );
  --child-shadow: none;

  &:before {
    content: '';
    position: absolute;
    width: 100%;
    height: 100%;
    z-index: $zindex-popover;
    pointer-events: none;
    box-shadow: var(--child-shadow);
  }
}

@keyframes scroll-shadow-inset {
  /* start with inset shadow on right */
  from {
    --child-shadow: inset -10px -10px 15px 0px rgb(0 0 0 / 0.3);
  }

  /* end with inset shadow on left */
  to {
    --child-shadow: inset 10px -10px 15px 0px rgb(0 0 0 / 0.3);
  }
}
```

**Comment by zipymonkey** [comment]
Setting position relative fixes the height issue BUT then the `:before` pseudo element then scrolls.  This stack overflow https://stackoverflow.com/a/54576406 adds another div around the content that handles the scrolling.  This would require replacing the https://www.drupal.org/project/table_bs_filter with our own thing to use.

**Comment by zipymonkey** [comment]
We could possibly use the new scroll-state container query.   This is doesn't have Firefox or Safari support but looks like it is in the w3 standards so there should be more support in the future.

## Links
- https://caniuse.com/?search=scroll-state
- https://developer.chrome.com/blog/css-scroll-state-queries
- https://nerdy.dev/4-css-features-every-front-end-developer-should-know-in-2026#@container-scroll-state()

**Comment by zipymonkey** [comment]
Tried something like the following but the after also scrolls.   Punting this again. 

```css
.table-responsive {
  /* Example 1: opacity variables for animating */
  @property --scroll-shadow-color-left-opacity {
    syntax: "<percentage>";
    inherits: false;
    initial-value: 0%;
  }

  @property --scroll-shadow-color-right-opacity {
    syntax: "<percentage>";
    inherits: false;
    initial-value: 0%;
  }

  container-type: scroll-state;
  position: relative;

  &::after {
    --scroll-bg: none;

    position: relative;
    @container scroll-state(scrollable: right) {
      --scroll-bg: linear-gradient(to left, #999, #0000 20px);
    }

    @container scroll-state(scrollable: left) {
      --scroll-bg: linear-gradient(to right, #999, #0000 20px);
    }

    @container scroll-state((scrollable: left) and (scrollable: right)) {
      --scroll-bg: linear-gradient(to left, #999, #0000 20px), linear-gradient(to right, #999, #0000 20px);
    }

    content: ' ';
    position: absolute;
    height: calc(100% - 1rem);
    width: 100cqw;
    left: 0;
    top: 0;
    z-index: 1;
    pointer-events: none;

    background: var(--scroll-bg);
  }


}
```
