### ISSUE TITLE
Peripheral: Add btn-default style

### ISSUE THREAD

**Issue by zipymonkey** [psu-libraries/psulib_base#313]
Bootstrap3 has a btn-default style that does not existing in Bootstrap5. We should add this style to the bootstrap3 peripheral styles so the default button styles match the primary button.  The following styles should work.

```css
/* Apply primary styles to default buttons */
.btn.btn-default {
  --bs-btn-bg: #005fa9;
  --bs-btn-color: #fff;
  --bs-btn-border-color: #005fa9;
  --bs-btn-hover-bg: #001e44;
  --bs-btn-hover-border-color: #001e44;
  --bs-btn-hover-color: #fff;
}
```

## Acceptance Criteria
- Update bootstrap3 peripheral styles
- Add example button to bootstrap3 peripheral demo
